# Generated by Django 4.1.7 on 2023-03-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60)),
                ('password', models.CharField(max_length=100)),
                ('nick', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
